#! /bin/bash

# usage:
#  see-graph name
#
# Shows graph named 'name' on the screen. For example:  see e200g20
#
# Graph must be stored in file named 'out'.

sed -n "/^digraph $1/,/^}/p" out > $1.dot &&
dot -Tpdf < $1.dot > $1.pdf &&
evince $1.pdf
