#! /bin/bash

# usage:
#  see-graph name [sa-output-file]
#
# Shows graph named 'name' on the screen. For example:  see e200g20
#
# The default sa-output-file to search is 'out'.

if [ `uname -s` = Darwin ]
then
  VIEW_PDF=open
else
  VIEW_PDF=evince
fi

if [ -z $2 ]
then
  OUT=out   # The default input file is 'out'
else
  OUT="$2"
fi

sed -n "/^digraph $1/{
  p
  :loop
  n
  p
  /^}/q
  b loop
}" "$OUT" > $1.dot &&
dot -Tpdf < $1.dot > $1.pdf &&
$VIEW_PDF $1.pdf
